# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dfe09dbe713b6b23434f185899a168a82f187de5b6aaa3b9497600a9d8bc26b844314116831e1d0dbb9409e108da34f291c84dbee8ec690a2d1949cf612961a7

test:
  secret_key_base: 7693cc9d1672b0bfeeba18e5ccea2bc1f35481d04ab7c0eae1f071c261655ab988825d8141dcefc4e0d350688e5ba586897940e8de6879e52a82c43c6a1a11ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
